name: Code Review with OpenAI

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Action
        run: yarn build

      - name: AI Code Reviewer
        uses: ./.
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AI_PROVIDER: "google" # or "anthropic" or "google"
          AI_API_KEY: ${{ secrets.GOOGLE_AI_KEY }}
          AI_MODEL: "gemini-2.5-pro-exp-03-25"
          AI_TEMPERATURE: 0.3 # 0 to 1 - higher values = more creativity and variance
          MAX_COMMENTS: 5 # Optional: defaults to 10
          APPROVE_REVIEWS: false # Optional: defaults to false
          EXCLUDE_PATTERNS: "yarn.lock,dist/**"
